[versions]
agp = "8.8.1"
android-compileSdk = "35"
android-minSdk = "27"
android-targetSdk = "35"
androidx-activityCompose = "1.10.0"
androidx-lifecycle = "2.8.4"
circuitFoundation = "0.24.0"
compose-plugin = "1.7.1"
composeDnd = "0.3.0"
coreSplashscreen = "1.0.1"
filekitCore = "0.8.2"
kmpfileFilekit = "0.6.0"
kotlin = "2.1.10"
kotlinx-coroutines = "1.10.1"
kotlinxDatetime = "0.6.1"
kotlinxIoCore = "0.6.0"
kotlinxSerializationJson = "1.7.3"
materialKolor = "2.0.0"
multiplatformSettingsNoArg = "1.2.0"
napier = "2.7.1"
okio = "3.9.1"
permissions = "0.18.0"
adaptive = "1.0.1"
slf4j = "2.0.16"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
circuit-foundation = { module = "com.slack.circuit:circuit-foundation", version.ref = "circuitFoundation" }
circuit-overlay = { module = "com.slack.circuit:circuit-overlay", version.ref = "circuitFoundation" }
compose-dnd = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "composeDnd" }
filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekitCore" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekitCore" }
kmpfile = { module = "dev.zwander:kmpfile", version.ref = "kmpfileFilekit" }
kmpfile-filekit = { module = "dev.zwander:kmpfile-filekit", version.ref = "kmpfileFilekit" }
kmpfile-okio = { module = "dev.zwander:kmpfile-okio", version.ref = "kmpfileFilekit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettingsNoArg" }
multiplatform-settings-serialization = { module = "com.russhwolf:multiplatform-settings-serialization", version.ref = "multiplatformSettingsNoArg" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissions" }
permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "permissions" }
permissions-test = { module = "dev.icerock.moko:permissions-test", version.ref = "permissions" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref= "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref= "slf4j" }
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
